[sddm-theme]
src.git = "https://github.com/L4ki/Dexy-Plasma-Themes"
fetch.github = "L4ki/Dexy-Plasma-Themes"

[copilot-vim]
src.git = "https://github.com/github/copilot.vim"
fetch.github = "github/copilot.vim"

[nvim-cokeline]
src.git = "https://github.com/noib3/nvim-cokeline"
fetch.github = "noib3/nvim-cokeline"

[move-nvim]
src.git = "https://github.com/fedepujol/move.nvim"
fetch.github = "fedepujol/move.nvim"

[openasar]
src.git = "https://github.com/GooseMod/OpenAsar"
fetch.github = "GooseMod/OpenAsar"

[zscroll]
src.git = "https://github.com/noctuid/zscroll"
fetch.github = "noctuid/zscroll"

[sddm]
src.git = "https://github.com/sddm/sddm"
fetch.github = "sddm/sddm"

