[alternate-toggler-nvim]
src.git = "https://github.com/rmagatti/alternate-toggler"
fetch.github = "rmagatti/alternate-toggler"

[copilot-vim]
src.git = "https://github.com/github/copilot.vim"
fetch.github = "github/copilot.vim"

[move-nvim]
src.git = "https://github.com/fedepujol/move.nvim"
fetch.github = "fedepujol/move.nvim"

[nvim-cokeline]
src.git = "https://github.com/noib3/nvim-cokeline"
fetch.github = "noib3/nvim-cokeline"
