[copilot-vim]
src.git = "https://github.com/github/copilot.vim"
fetch.github = "github/copilot.vim"

[nvim-cokeline]
src.git = "https://github.com/noib3/nvim-cokeline"
fetch.github = "noib3/nvim-cokeline"

[zscroll]
src.git = "https://github.com/noctuid/zscroll"
fetch.github = "noctuid/zscroll"

[openasar]
src.git = "https://github.com/GooseMod/OpenAsar"
fetch.github = "GooseMod/OpenAsar"
