[alternate-toggler-nvim]
src.git = "https://github.com/rmagatti/alternate-toggler"
fetch.github = "rmagatti/alternate-toggler"

[barbar-nvim]
src.git = "https://github.com/romgrk/barbar.nvim"
fetch.github = "romgrk/barbar.nvim"

[catppuccin-nvim]
src.git = "https://github.com/catppuccin/nvim"
fetch.github = "catppuccin/nvim"

[codeium-vim]
src.git = "https://github.com/Exafunction/codeium.vim"
fetch.github = "Exafunction/codeium.vim"

[copilot-vim]
src.git = "https://github.com/github/copilot.vim"
fetch.github = "github/copilot.vim"

[emmet-vim]
src.git = "https://github.com/mattn/emmet-vim"
fetch.github = "mattn/emmet-vim"

# [move-nvim]
# src.git = "https://github.com/fedepujol/move.nvim"
# fetch.github = "fedepujol/move.nvim"

[illuminate-nvim]
src.git = "https://github.com/RRethy/vim-illuminate"
fetch.github = "RRethy/vim-illuminate"

[navbuddy-nvim]
src.git = "https://github.com/SmiteshP/nvim-navbuddy"
fetch.github = "SmiteshP/nvim-navbuddy"

[navic-nvim]
src.git = "https://github.com/SmiteshP/nvim-navic"
fetch.github = "SmiteshP/nvim-navic"

[overseer-nvim]
src.git = "https://github.com/stevearc/overseer.nvim"
fetch.github = "stevearc/overseer.nvim"
